# Generated by Django 5.0.3 on 2024-03-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDataPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='name', max_length=255)),
                ('value', models.CharField(help_text='name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(help_text='name', max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('ingridients', models.TextField()),
                ('note', models.TextField()),
                ('recipe_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.recipedata')),
            ],
        ),
        migrations.AddField(
            model_name='recipedata',
            name='recipe_pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.recipedatapair'),
        ),
        migrations.CreateModel(
            name='RecipeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe')),
            ],
        ),
    ]
