# Generated by Django 5.0.3 on 2024-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_recipedata_recipe_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
