# Generated by Django 5.0.3 on 2024-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_recipe_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinfo',
            name='cook_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='recipeinfo',
            name='servings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipeinfo',
            name='total_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipeinfo',
            name='prep_time',
            field=models.TimeField(null=True),
        ),
    ]
