# Generated by Django 5.0.3 on 2024-03-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(help_text='name', max_length=255), max_length=255, verbose_name='Category Slug'),
        ),
    ]
