# Generated by Django 5.0.3 on 2024-03-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
